services:
  postgres:
    container_name: database
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: paylog
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  server:
    container_name: server
    build: 
      context: ./server
      dockerfile: Dockerfile
    restart: always
    depends_on:
      - postgres
    environment:
        DATABASE_URL: postgresql://postgres:postgres@postgres:5432/paylog
    ports:
      - "3000:3000"
    volumes:
      - ./server:/app
    
  client:
    container_name: client
    build:
      context: ./client
      dockerfile: Dockerfile
    restart: always
    depends_on:
      - server
    ports:
      - "5173:5173"
    volumes:
      - ./client:/app

volumes:
  postgres_data:
